### ISSUE TITLE
Throwing informative error when experiment enrollment start fails

### ISSUE THREAD

**Issue by RidhamShah** [CarnegieLearningWeb/UpGrade#242] opened 2022-02-02 10:52 UTC
Right now if the experiment fails to start enrolling, the server throws a 500 error. We need to throw a more specific error with more information. The error in this issue is related to users with a NULL user ID in the backend that the system was trying to exclude at the start of the experiment. At the start of each experiment, we exclude all users who have visited the experiment points and IDs in the experiment. If any user is has a NULL ID, the code is throwing an error.

**Comment by nirmalpatel** [comment] 2022-02-03 13:54
Duplicate of #240

**Closed by nirmalpatel** 2022-02-03 13:54 UTC
