### ISSUE TITLE
Create client testing apps

### ISSUE THREAD

**Issue by mswartzCL** [CarnegieLearningWeb/UpGrade#856] opened 2023-05-17 18:08 UTC

**Comment by danoswaltCL** [comment] 2023-05-17 19:18
shape-up pitch:

Problem:
End-to-end testing of client library and API changes currently leans heavily on Mathia and other active consumers of the library to implement new versions of UpGrade in staging environments. This coupling ties us heavily to factors outside of our control, which can greatly slow down and complicate release testing beyond the actual feature(s) being tested, especially if there bugfixes, we have to start over. It makes regression testing different versions and compatibility pretty hard. It also makes utilization of a 6 week constraint for a shape-up cycle pretty much impossible.

The ideal state will be a release cycle that is entirely independent of any using real library/API consumers if we want to be able to develop -> test -> release a feature to prod with minimal friction from dependencies. To accomplish this, we really just need a dedicated dummy client app or two for testing the supported client library versions against various backend versions.

Appetite:
A worthwhile solution might take 1-2 weeks.

Solution:
An MVP might be a dummy java client backend app that is set up to communicate with a dummy frontend that can be used like a user, much like the demo app (but not the demo app!). This would be for manual testing in the MVP version, but one can easily imagine automated regression tests (maybe that's a rabbit hole??).

We should be able to easily toggle / configure which published builds (or local builds) of the client library we want to test, and the host url of the backend API. It should be easy to build out dummy components that have various decision points for whatever scenarios / experiments we want to test.

For example, in this app we could have multiple scenarios set up, such as a component could be set up as a Mathia-lite simulation for version 1x of the library, another could be set up as a Mathia-lite simulation for version 3x, and another for 4x. I should be able to point at whatever version of backend API I want and be able to easily test all 3 of those scenarios. This would be extremely time-consuming to test in Mathia by alone.

I also think it will help us empathize with clients trying to implement code to work with our library, e.g. we may spot client-lib user experience pitfalls more quickly. Zack is always more sensitive to how the client-lib is used because he has to make it work in demo app, and same with Matt in Mathia.

Rabbit-Holes:
The dummy apps should be kept narrowly focused on testing client-library versions against various backend versions. We should not repurpose the demo-app for testing, no matter how convenient! And we should be very wary of using these for too much automated testing, as that may become a maintenance headache over time.

No-gos:
This isn't something that will be released to public, so other than whiddling away too much time on it, I'm not sure what would make this a complete bust.

**Comment by VivekFitkariwala** [comment] 2023-05-18 13:17
Should we convert the code to monorepo?
So that testing client lib (at least js client) with test app will get easy. And also linking `upgrade-types` with `client-sdk`, `frontend` and `backend` will be easy.

**Comment by danoswaltCL** [comment] 2023-05-18 15:20
@VivekFitkariwala Absolutely, I plan on this being in monorepo as being something that is meant to be run locally by a developer, with ability to have locally built assets available to test in the app as well as pre-loading in any previously published client-lib artifacts.

The goal will be able to fire up the client-lib-testing tool UI, a mock-client-app backend (if testing backend like java), and an API host:

1) pick an UpGrade API host url
2) pick a mock-client-app scenario (could be front or backend app, this will determine how to route requests)
3) pick a client-lib version

An experiment for the mock-client-app context will need to be enrolling with sites and targets that exist in the mock-client-app scenario.

And then in the interface, I imagine a few fields to create and initialize a user, and a set of buttons that will represent decision points, where where I click them, I'll get some condition or payload text. Some logging can be sent over to UI potentially also.

For example, if testing a mock-mathia java app, my mock-java-server will be running, and my requests in the test-UI will be routed to a service class (the mock-client-app scenario). All the client-lib versions for Java will have been preloaded when built, so the requests will go to that scenario class that is coded up like a client app, which will construct a client lib object of the correct version, initialized with the host url given.

My intent is to focus on Java client lib testing first because that's our bottleneck, but you should be able to pick a frontend client-app scenario that will work exactly the same, except the requests will route to mock front-end service components loaded up with the tester-ui that use a frontend client-lib instead of fetching from backend. Likewise, we should be able to test requests to other theoretical mock-client-app backends also, like a Typescript/Express or C# if we get around to it!

That way I can quickly compare mock scenarios with any combination of API version, Client-lib version, and mocked Client App Code scenarios for whatever we intend to support.

This all works great in my head, please let me know if I'm skipping important details.

**Comment by VivekFitkariwala** [comment] 2023-05-19 11:43
That's an interesting idea. For javascript client-sdk you can install multiple versions of the same packages as an alias and you can just add test cases for different versions.
I don't see even if we need UI for this. Just a test runner is enough.

**Closed** 2023-06-23 18:37 UTC
