### ISSUE TITLE
Student who has visited a decision point prior to an experiment is not being excluded

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#570] opened 2022-10-17 14:42 UTC
**Describe the bug**
The student who has visited a decision point prior to an experiment should be excluded from the experiment (if the "Exclude If Reached" is enabled). But it seems like the student is not being excluded from the experiment (unless I'm missing something).

**To Reproduce**
1. Create an experiment with a "Exclude If Reached"  decision point 
2. Make a `POST api/init` request
3. Make a `POST api/assign` request
4. Make a `POST api/mark` request
5. Change the experiment status to "Enrolling"
6. Refresh the page and check the "Participants Excluded" is still 0
7. Make a `POST api/init` request
8. Make a `POST api/assign` request
9. You will see that the student is assigned to a condition which means the student is not excluded from the experiment

**Expected behavior**
In step 6, the "Participants Excluded" should be updated to 1 and the `POST api/assign` request should return an empty array.

**Videos**
1. Student not being excluded properly (Using the latest version of UpGrade)
https://user-images.githubusercontent.com/90279765/196207102-e30f0eb8-5711-4433-997b-099ee3456d97.mov

2. Student being excluded properly (Using the old UpGrade used in the demo app)
https://user-images.githubusercontent.com/90279765/196206771-4130f325-5128-41d0-99e6-ab458d086b0e.mov

**Comment by danoswaltCL** [comment] 2022-10-17 14:50
hey @zackcl this is a known issue that I looked into in depth, although I did not make a github issues about it formally.

Please see if this is same issue:
https://carnegielearning.slack.com/archives/CTD5UG8R2/p1664553100851899

**Comment by zackcl** [comment] 2022-10-17 15:19
@danoswaltCL I think it's a different issue. What you posted is about whether the consistency rule is ignored or not depending on the `exclude_if_reached` state. My issue is not about the consistency rule (I'm just using the "Individual" consistency rule) but about a previously visited student not being excluded from an active experiment.

**Comment by danoswaltCL** [comment] 2022-10-17 15:38
The issue I documented for "individual consistency" would be that "exclude_if_reached" must be true if you want students to be excluded in the current code. If "exclude_if_reached" is false / unchecked, then "Individual consistency" is being ignored. Is the decision point for your steps to reproduce marked as true for "exclude_if_reached"?

**Comment by zackcl** [comment] 2022-10-17 15:58
@danoswaltCL Yes, please check out the 2 videos I posted.

**Comment by ppratikcr7** [comment] 2022-10-19 07:33
@zackcl I am looking into this.

**Comment by danoswaltCL** [comment] 2022-10-19 13:24
To add a note: I had previously commented in slack several different ways in which the consistency rules and exclude_if_reached were not working as expected: https://carnegielearning.slack.com/archives/CTD5UG8R2/p1664553100851899

But in the latest code, I guess after the pooling logic went in, the bug has changed again and is simpler to explain: now it looks as if nobody gets excluded due to prior visits to a decision point in any scenario, no matter what consistency or exclude_if_reached rule is used.

**Closed** 2022-10-24 18:00 UTC
Labels: bug
