### ISSUE TITLE
Condition alias duplicates

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#708] opened 2023-02-02 19:42 UTC
**Describe the bug**
When editing an experiment with condition aliases, sometimes duplicate condition aliases will get created with different ids, resulting into multiple copies of condition aliases inserted into database and also therefore attached to the experiment object.

**To Reproduce**
Not exactly known yet, will put steps when I can make it happen.

**Expected behavior**
This should not happen, but also some extra validation on front and/or backend to ensure that experiment object isn't malformed when being created or modified (like for instance, a count of condition aliases would ensure that only the expected number are sent).

Both simple and factorial should be checked.

**Comment by jreddig** [comment] 2023-08-11 12:40
@danoswaltCL since we closed this, can we move it to "Done" rather than "QA"? Or is this something we still want to look into? I don't see attached pull requests or related commits in the commit history

**Comment by danoswaltCL** [comment] 2023-08-11 13:30
yeah this is just done

**Comment by danoswaltCL** [comment] 2023-10-19 18:41
This is potentially happening again, or something like it. Will look into this.

**Comment by Yagnik56** [comment] 2023-10-25 09:28
@danoswaltCL can you provide more details on this, I have tried to look into it but not able to recreate it. let me know if you have specific scenario when this issue was coming.

**Comment by amurphy-cl** [comment] 2023-10-25 14:22
@Yagnik56 I recreated this by creating a new experiment in staging with payloads and exporting the json. Them I imported the experiment in production. The import removed all the payload values (issue #1074) and also duplicated the existing (incorrect) values. Here's an example json from one such created experiment -- it has 6 payload values where there should be only 3. 
[test payloads.json](https://github.com/CarnegieLearningWeb/UpGrade/files/13167118/test.payloads.json)

**Comment by Yagnik56** [comment] 2023-10-26 13:17
will it be possible for you to share video of same, I tried myself but not able recreate same following the way you suggested.

**Comment by Yagnik56** [comment] 2023-10-27 08:00
Did you delete the experiment before importing that, I am not able to see wrong value added in payload but not able to see duplicate values. Also I think this issue might be resolved when we resolve issue #1074. I will look into it deeper but I think this [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/1055) will fix this issue as well.

**Comment by amurphy-cl** [comment] 2023-10-27 12:51
Yes, I deleted the experiment before re-importing. Note that the duplication doesn't happen in the UI, only the raw json. @danoswaltCL do you have any additional detail to add?

**Comment by amurphy-cl** [comment] 2023-10-27 14:10
Here's what we saw -- the error appears to be in the conditions array

<img width="827" alt="image" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/9b2e856d-accd-469e-8887-6b5c454f248c">

**Comment by zackcl** [comment] 2023-11-06 14:39
@zackcl I need to test this.

**Comment by zackcl** [comment] 2023-11-07 14:20
I can confirm that this issue has been resolved; I have not observed any duplicated payload values.

```
    "conditions": [
        {
            "createdAt": "2023-11-07T13:38:24.876Z",
            "updatedAt": "2023-11-07T13:38:24.876Z",
            "versionNumber": 1,
            "id": "f7e5cb8d-b644-4c58-973f-f9074840eede",
            "twoCharacterId": "VQ",
            "name": "",
            "description": null,
            "conditionCode": "variant",
            "assignmentWeight": 50,
            "order": 2,
            "conditionPayloads": [
                {
                    "createdAt": "2023-11-07T13:38:24.876Z",
                    "updatedAt": "2023-11-07T13:38:24.876Z",
                    "versionNumber": 1,
                    "id": "757794ff-1108-4895-8c1f-337ce91d9631",
                    "payloadValue": "my_alias2",
                    "payloadType": "string"
                }
            ],
            "levelCombinationElements": []
        },
        {
            "createdAt": "2023-11-07T13:38:24.876Z",
            "updatedAt": "2023-11-07T13:38:24.876Z",
            "versionNumber": 1,
            "id": "1e6de8a1-86ab-4a26-aa0a-b1c1296d79a5",
            "twoCharacterId": "V6",
            "name": "",
            "description": null,
            "conditionCode": "control",
            "assignmentWeight": 50,
            "order": 1,
            "conditionPayloads": [
                {
                    "createdAt": "2023-11-07T13:38:24.876Z",
                    "updatedAt": "2023-11-07T13:38:24.876Z",
                    "versionNumber": 1,
                    "id": "2c4b36d1-f0bd-45ad-85dc-426b60a83b93",
                    "payloadValue": "my_alias1",
                    "payloadType": "string"
                }
            ],
            "levelCombinationElements": []
        }
    ],
```

Here are the exported JSON experiment files from the dev branch:

Simple: 

[alias-duplicate-test.json](https://github.com/CarnegieLearningWeb/UpGrade/files/13281401/alias-duplicate-test.json)

Factorial:

[fact_alias_test.json](https://github.com/CarnegieLearningWeb/UpGrade/files/13281406/fact_alias_test.json)

**Comment by zackcl** [comment] 2023-11-07 15:22
QA Check Completed: All tests have passed successfully.

**Closed by zackcl** 2023-11-07 15:22 UTC
Labels: bug, priority: high
